-- M0.5 AI Lesson Generator: a dedicated draft course for AI-generated content.
--
-- `published` only exists at the courses level in this schema (see 0001_init.sql).
-- The existing seed course is already published=true with real items, so writing
-- unreviewed AI-generated content into it would make it instantly visible to any
-- child. Instead, generated lessons land under this separate, unpublished course;
-- a human reviews and approves each generated unit, which moves it into the
-- published seed course before it becomes playable.
--
-- The Edge Function creates a new unit/lesson/activity/items per generation call
-- under this fixed course id; only the course itself needs to pre-exist.

insert into public.courses (id, title, ui_language, target_language, description, published)
values ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        'AI-Generated Lessons (Draft)', 'en', 'ja',
        'Lessons generated by the M0.5 AI Lesson Generator, pending review. '
        'Approve reviewed units to move them into the published course.',
        false)
on conflict (id) do nothing;
